# Generated by Django 3.2.4 on 2021-09-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersback',
            name='animes_fav',
            field=models.ManyToManyField(to='pages.Anime'),
        ),
    ]
