# Generated by Django 3.2.4 on 2021-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usersback_animes_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
