# Generated by Django 3.2.4 on 2021-10-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_animedate_options'),
        ('account', '0002_done_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done_show',
            name='animes',
            field=models.ManyToManyField(blank=True, to='pages.Anime'),
        ),
    ]
