# Generated by Django 3.2.4 on 2021-10-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_animedate_options'),
        ('account', '0003_alter_done_show_animes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersback',
            name='animes_fav',
            field=models.ManyToManyField(blank=True, to='pages.Anime'),
        ),
    ]
