# Generated by Django 3.2.4 on 2021-10-28 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20211026_0640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_want_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='done_show',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersback',
            name='prive',
            field=models.CharField(blank=True, choices=[('prive', 'prive'), ('public', 'public')], default='prive', max_length=150),
        ),
        migrations.AddField(
            model_name='usersback',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='want_show',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.ManyToManyField(blank=True, to='pages.Anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
