# Generated by Django 3.2.4 on 2021-10-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211028_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
    ]
