# Generated by Django 3.2.4 on 2021-10-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211028_0523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='following',
        ),
    ]
