# Generated by Django 3.2.4 on 2021-10-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211028_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersback',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='usersback',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/def/user-default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='usersback',
            name='social_github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='social_linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='social_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
