# Generated by Django 3.2.4 on 2021-10-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211029_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usersback',
            name='username',
        ),
        migrations.AlterField(
            model_name='usersback',
            name='profile_image',
            field=models.ImageField(blank=True, default='photos/profiles/def/user-default.png', null=True, upload_to='photos/profiles/'),
        ),
    ]
