# Generated by Django 3.2.4 on 2021-10-29 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20211029_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
