# Generated by Django 3.2.4 on 2021-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_tokens_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersback',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
