# Generated by Django 3.2.4 on 2021-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_usersback_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersback',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
