# Generated by Django 3.2.8 on 2021-10-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersback',
            old_name='social_linkedin',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='usersback',
            old_name='social_youtube',
            new_name='social_instagram',
        ),
    ]
