# Generated by Django 3.2.8 on 2021-10-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20211030_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersback',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersback',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
