# Generated by Django 3.2.8 on 2021-10-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20211030_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersback',
            name='prive',
        ),
        migrations.AddField(
            model_name='usersback',
            name='information_public',
            field=models.BooleanField(default=True),
        ),
    ]
