# Generated by Django 3.2.8 on 2021-10-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20211030_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersback',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/def/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
