# Generated by Django 3.2.8 on 2021-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_usersback_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersback',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
