# Generated by Django 3.2.4 on 2021-10-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animedate',
            options={'ordering': ['-name']},
        ),
    ]
