# Generated by Django 3.2.4 on 2021-10-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210928_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='image_episode',
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_anime',
            field=models.ImageField(default='', upload_to='photos/anime'),
        ),
    ]
