# Generated by Django 3.2.4 on 2021-10-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211014_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='episode',
            field=models.CharField(max_length=50),
        ),
    ]
