# Generated by Django 3.2.4 on 2021-10-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_anime_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='episode_date',
        ),
    ]
